<?php
/**
 *  Copyright 2011 Peter Hilbring <kontakt@hilbring-online.de>
 *
 *  Licensed under the Apache License, Version 2.0 (the "License"); you may
 *  not use this file except in compliance with the License. You may obtain
 *  a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 *  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 *  License for the specific language governing permissions and limitations
 *  under the License.
 *
 * @author    Peter Hilbring <kontakt@hilbring-online.de>
 * @package   HSLColor
 * @copyright Copyright (c) 2011 Peter Hilbring (http://www.hilbring.de)
 * @license   http://www.apache.org/licenses/LICENSE-2.0     Apache License, Version 2.0
 */

require_once dirname(__FILE__) . '/../HSLColor.class.php';

/**
 * Test class for HSLColor.
 * Generated by PHPUnit on 2011-09-07 at 09:47:39.
 */
class HSLColorTest extends PHPUnit_Framework_TestCase {

    /**
     * @var HSLColor
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
	$this->object = new HSLColor;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @todo Implement testSetHSL().
     */
    public function testSetHSL() {
	// Remove the following lines when you implement this test.
	$this->markTestIncomplete(
		'This test has not been implemented yet.'
	);
    }

    /**
     * @todo Implement testSetRGB().
     */
    public function testSetRGB() {
	// Remove the following lines when you implement this test.
	$this->markTestIncomplete(
		'This test has not been implemented yet.'
	);
    }

    /**
     * @todo Implement testSetRGBString().
     */
    public function testSetRGBString() {
	// Remove the following lines when you implement this test.
	$this->markTestIncomplete(
		'This test has not been implemented yet.'
	);
    }

    /**
     * @todo Implement testGetHSL().
     */
    public function testGetHSL() {
	// Remove the following lines when you implement this test.
	$this->markTestIncomplete(
		'This test has not been implemented yet.'
	);
    }

    /**
     * @todo Implement testGetRGB().
     */
    public function testGetRGB() {
	// Remove the following lines when you implement this test.
	$this->markTestIncomplete(
		'This test has not been implemented yet.'
	);
    }

    /**
     * @todo Implement testGetRGBString().
     */
    public function testGetRGBString() {
	// Remove the following lines when you implement this test.
	$this->markTestIncomplete(
		'This test has not been implemented yet.'
	);
    }

    /**
     * @todo Implement testChangeHue().
     */
    public function testChangeHue() {
	// Remove the following lines when you implement this test.
	$this->markTestIncomplete(
		'This test has not been implemented yet.'
	);
    }

    /**
     * @todo Implement testChangeSaturation().
     */
    public function testChangeSaturation() {
	// Remove the following lines when you implement this test.
	$this->markTestIncomplete(
		'This test has not been implemented yet.'
	);
    }

    /**
     * @todo Implement testChangeLightness().
     */
    public function testChangeLightness() {
	// Remove the following lines when you implement this test.
	$this->markTestIncomplete(
		'This test has not been implemented yet.'
	);
    }

    /**
     * @todo Implement testGetTriadic().
     */
    public function testGetTriadic() {
	// Remove the following lines when you implement this test.
	$this->markTestIncomplete(
		'This test has not been implemented yet.'
	);
    }

    /**
     * @todo Implement testGetSplitComplements().
     */
    public function testGetSplitComplements() {
	// Remove the following lines when you implement this test.
	$this->markTestIncomplete(
		'This test has not been implemented yet.'
	);
    }

    /**
     * @todo Implement testGetAnalogous().
     */
    public function testGetAnalogous() {
	// Remove the following lines when you implement this test.
	$this->markTestIncomplete(
		'This test has not been implemented yet.'
	);
    }

    public function testGetComplement27() {
		$this->object->setHSL( 27.0, 0.3, 0.6 );
		$complement = $this->object->getComplement();
		$ret = $complement->getHSL();
		$this->assertEquals( 27.0 + 180.0, $ret['h'], "Wert: 27.0, Erwartet: " . 27.0 + 180.0 . ", Erhalten: " . $ret['h'] );
	}

    public function testGetComplement180() {
		$this->object->setHSL( 180.0, 0.3, 0.6 );
		$complement = $this->object->getComplement();
		$ret = $complement->getHSL();
		$this->assertEquals( 0.0, $ret['h'], "Wert: 180.0, Erwartet: 0.0, Erhalten: " . $ret['h'] );
	}

    public function testShortRGBStringToRGBRValue() {
		$this->object->setRGBString( '123' );
		$ret = $this->object->getRGB();
		$this->assertEquals( 1 * 16 + 1, $ret['r'], "Erwartet: " . 1 * 16 + 1 . ", Erhalten: " . $ret['r'] );
    }

    public function testShortRGBStringToRGBGValue() {
		$this->object->setRGBString( '123' );
		$ret = $this->object->getRGB();
		$this->assertEquals( 2 * 16 + 2, $ret['g'], "Erwartet: " . 2 * 16 + 2 . ", Erhalten: " . $ret['g'] );
    }

    public function testShortRGBStringToRGBBValue() {
		$this->object->setRGBString( '123' );
		$ret = $this->object->getRGB();
		$this->assertEquals( 3 * 16 + 3, $ret['b'], "Erwartet: " . 3 * 16 + 3 . ", Erhalten: " . $ret['b'] );
    }

	/**
	 * Genauigkeit 5‰ (ALT-0137)
	 * @dataProvider colorTableProvider
	 */
    public function testRGBToHValue( $name, $hex, $rgb, $hsl, $hsv, $cmy, $cmyk ) {
		$this->object->setRGB( $rgb['r'], $rgb['g'], $rgb['b'] );
		$ret = $this->object->getHSL();
		$this->assertEquals( $hsl['h'], $ret['h'], "Farbe: $name, Erwartet: " . $hsl['h'] . ", Erhalten: " . $ret['h'], 0.005 );
    }

	/**
	 * Genauigkeit 5‰ (ALT-0137)
	 * @dataProvider colorTableProvider
	 */
    public function testRGBToSValue( $name, $hex, $rgb, $hsl, $hsv, $cmy, $cmyk ) {
		$this->object->setRGB( $rgb['r'], $rgb['g'], $rgb['b'] );
		$ret = $this->object->getHSL();
		$this->assertEquals( $hsl['s'], $ret['s'], "Farbe: $name, Erwartet: " . $hsl['s'] . ", Erhalten: " . $ret['s'], 0.005 );
    }

	/**
	 * Genauigkeit 5‰ (ALT-0137)
	 * @dataProvider colorTableProvider
	 */
    public function testRGBToLValue( $name, $hex, $rgb, $hsl, $hsv, $cmy, $cmyk ) {
		$this->object->setRGB( $rgb['r'], $rgb['g'], $rgb['b'] );
		$ret = $this->object->getHSL();
		$this->assertEquals( $hsl['l'], $ret['l'], "Farbe: $name, Erwartet: " . $hsl['l'] . ", Erhalten: " . $ret['l'], 0.005 );
    }

	/**
	 * Rundungstoleranzen, daher Delta 2
	 * @dataProvider colorTableProvider
	 */
    public function testHSLToRGBString( $name, $hex, $rgb, $hsl, $hsv, $cmy, $cmyk ) {
		$this->object->setHSL( $hsl['h'], $hsl['s'], $hsl['l'] );
		$ret = $this->object->getRGBString();
		$this->assertTrue( $this->isSimilar( $hex, $ret, 2 ), "Farbe: $name, Erwartet: $hex, Erhalten: $ret" );
    }

	/**
	 * @dataProvider colorTableProvider
	 */
	public function testNamesToRGBString( $name, $hex, $rgb, $hsl, $hsv, $cmy, $cmyk ) {
		$this->object->setRGBString( $name );
		$ret = $this->object->getRGBString();
		$this->assertEquals( $hex, $ret, "Farbe: $name, Erwartet: $hex, Erhalten: $ret" );
	}

	public function colorTableProvider() {
		return array(
			array( 'aliceblue', '#F0F8FF', 'rgb' => array( 'r' => 240, 'g' => 248, 'b' => 255, ), 'hsl' => array( 'h' => 208.000, 's' => 1.000, 'l' => 0.971, ), 'hsv' => array( 'h' => 208.000, 's' => 0.059, 'v' => 1.000, ), 'cmy' => array( 'c' => 0.059, 'm' => 0.027, 'y' => 0.000, ), 'cmyk' => array( 'c' => 0.059, 'm' => 0.027, 'y' => 0.000, 'k' => 0.000, ), ),
			array( 'antiquewhite', '#FAEBD7', 'rgb' => array( 'r' => 250, 'g' => 235, 'b' => 215, ), 'hsl' => array( 'h' => 34.286, 's' => 0.778, 'l' => 0.912, ), 'hsv' => array( 'h' => 34.286, 's' => 0.140, 'v' => 0.980, ), 'cmy' => array( 'c' => 0.020, 'm' => 0.078, 'y' => 0.157, ), 'cmyk' => array( 'c' => 0.000, 'm' => 0.060, 'y' => 0.140, 'k' => 0.020, ), ),
			array( 'aqua', '#00FFFF', 'rgb' => array( 'r' => 0, 'g' => 255, 'b' => 255, ), 'hsl' => array( 'h' => 180.000, 's' => 1.000, 'l' => 0.500, ), 'hsv' => array( 'h' => 180.000, 's' => 1.000, 'v' => 1.000, ), 'cmy' => array( 'c' => 1.000, 'm' => 0.000, 'y' => 0.000, ), 'cmyk' => array( 'c' => 1.000, 'm' => 0.000, 'y' => 0.000, 'k' => 0.000, ), ),
			array( 'aquamarine', '#7FFFD4', 'rgb' => array( 'r' => 127, 'g' => 255, 'b' => 212, ), 'hsl' => array( 'h' => 159.844, 's' => 1.000, 'l' => 0.749, ), 'hsv' => array( 'h' => 159.844, 's' => 0.502, 'v' => 1.000, ), 'cmy' => array( 'c' => 0.502, 'm' => 0.000, 'y' => 0.169, ), 'cmyk' => array( 'c' => 0.502, 'm' => 0.000, 'y' => 0.169, 'k' => 0.000, ), ),
			array( 'azure', '#F0FFFF', 'rgb' => array( 'r' => 240, 'g' => 255, 'b' => 255, ), 'hsl' => array( 'h' => 180.000, 's' => 1.000, 'l' => 0.971, ), 'hsv' => array( 'h' => 180.000, 's' => 0.059, 'v' => 1.000, ), 'cmy' => array( 'c' => 0.059, 'm' => 0.000, 'y' => 0.000, ), 'cmyk' => array( 'c' => 0.059, 'm' => 0.000, 'y' => 0.000, 'k' => 0.000, ), ),
			array( 'beige', '#F5F5DC', 'rgb' => array( 'r' => 245, 'g' => 245, 'b' => 220, ), 'hsl' => array( 'h' => 60.000, 's' => 0.556, 'l' => 0.912, ), 'hsv' => array( 'h' => 60.000, 's' => 0.102, 'v' => 0.961, ), 'cmy' => array( 'c' => 0.039, 'm' => 0.039, 'y' => 0.137, ), 'cmyk' => array( 'c' => 0.000, 'm' => 0.000, 'y' => 0.102, 'k' => 0.039, ), ),
			array( 'bisque', '#FFE4C4', 'rgb' => array( 'r' => 255, 'g' => 228, 'b' => 196, ), 'hsl' => array( 'h' => 32.542, 's' => 1.000, 'l' => 0.884, ), 'hsv' => array( 'h' => 32.542, 's' => 0.231, 'v' => 1.000, ), 'cmy' => array( 'c' => 0.000, 'm' => 0.106, 'y' => 0.231, ), 'cmyk' => array( 'c' => 0.000, 'm' => 0.106, 'y' => 0.231, 'k' => 0.000, ), ),
			array( 'black', '#000000', 'rgb' => array( 'r' => 0, 'g' => 0, 'b' => 0, ), 'hsl' => array( 'h' => 0.000, 's' => 0.000, 'l' => 0.000, ), 'hsv' => array( 'h' => 0.000, 's' => 0.000, 'v' => 0.000, ), 'cmy' => array( 'c' => 1.000, 'm' => 1.000, 'y' => 1.000, ), 'cmyk' => array( 'c' => 0.000, 'm' => 0.000, 'y' => 0.000, 'k' => 1.000, ), ),
			array( 'blanchedalmond', '#FFEBCD', 'rgb' => array( 'r' => 255, 'g' => 235, 'b' => 205, ), 'hsl' => array( 'h' => 36.000, 's' => 1.000, 'l' => 0.902, ), 'hsv' => array( 'h' => 36.000, 's' => 0.196, 'v' => 1.000, ), 'cmy' => array( 'c' => 0.000, 'm' => 0.078, 'y' => 0.196, ), 'cmyk' => array( 'c' => 0.000, 'm' => 0.078, 'y' => 0.196, 'k' => 0.000, ), ),
			array( 'blue', '#0000FF', 'rgb' => array( 'r' => 0, 'g' => 0, 'b' => 255, ), 'hsl' => array( 'h' => 240.000, 's' => 1.000, 'l' => 0.500, ), 'hsv' => array( 'h' => 240.000, 's' => 1.000, 'v' => 1.000, ), 'cmy' => array( 'c' => 1.000, 'm' => 1.000, 'y' => 0.000, ), 'cmyk' => array( 'c' => 1.000, 'm' => 1.000, 'y' => 0.000, 'k' => 0.000, ), ),
			array( 'blueviolet', '#8A2BE2', 'rgb' => array( 'r' => 138, 'g' => 43, 'b' => 226, ), 'hsl' => array( 'h' => 271.148, 's' => 0.759, 'l' => 0.527, ), 'hsv' => array( 'h' => 271.148, 's' => 0.810, 'v' => 0.886, ), 'cmy' => array( 'c' => 0.459, 'm' => 0.831, 'y' => 0.114, ), 'cmyk' => array( 'c' => 0.389, 'm' => 0.810, 'y' => 0.000, 'k' => 0.114, ), ),
			array( 'brown', '#A52A2A', 'rgb' => array( 'r' => 165, 'g' => 42, 'b' => 42, ), 'hsl' => array( 'h' => 0.000, 's' => 0.594, 'l' => 0.406, ), 'hsv' => array( 'h' => 0.000, 's' => 0.745, 'v' => 0.647, ), 'cmy' => array( 'c' => 0.353, 'm' => 0.835, 'y' => 0.835, ), 'cmyk' => array( 'c' => 0.000, 'm' => 0.745, 'y' => 0.745, 'k' => 0.353, ), ),
			array( 'burlywood', '#DEB887', 'rgb' => array( 'r' => 222, 'g' => 184, 'b' => 135, ), 'hsl' => array( 'h' => 33.793, 's' => 0.569, 'l' => 0.700, ), 'hsv' => array( 'h' => 33.793, 's' => 0.392, 'v' => 0.871, ), 'cmy' => array( 'c' => 0.129, 'm' => 0.278, 'y' => 0.471, ), 'cmyk' => array( 'c' => 0.000, 'm' => 0.171, 'y' => 0.392, 'k' => 0.129, ), ),
			array( 'cadetblue', '#5F9EA0', 'rgb' => array( 'r' => 95, 'g' => 158, 'b' => 160, ), 'hsl' => array( 'h' => 181.846, 's' => 0.255, 'l' => 0.500, ), 'hsv' => array( 'h' => 181.846, 's' => 0.406, 'v' => 0.627, ), 'cmy' => array( 'c' => 0.627, 'm' => 0.380, 'y' => 0.373, ), 'cmyk' => array( 'c' => 0.406, 'm' => 0.013, 'y' => 0.000, 'k' => 0.373, ), ),
			array( 'chartreuse', '#7FFF00', 'rgb' => array( 'r' => 127, 'g' => 255, 'b' => 0, ), 'hsl' => array( 'h' => 90.118, 's' => 1.000, 'l' => 0.500, ), 'hsv' => array( 'h' => 90.118, 's' => 1.000, 'v' => 1.000, ), 'cmy' => array( 'c' => 0.502, 'm' => 0.000, 'y' => 1.000, ), 'cmyk' => array( 'c' => 0.502, 'm' => 0.000, 'y' => 1.000, 'k' => 0.000, ), ),
			array( 'chocolate', '#D2691E', 'rgb' => array( 'r' => 210, 'g' => 105, 'b' => 30, ), 'hsl' => array( 'h' => 25.000, 's' => 0.750, 'l' => 0.471, ), 'hsv' => array( 'h' => 25.000, 's' => 0.857, 'v' => 0.824, ), 'cmy' => array( 'c' => 0.176, 'm' => 0.588, 'y' => 0.882, ), 'cmyk' => array( 'c' => 0.000, 'm' => 0.500, 'y' => 0.857, 'k' => 0.176, ), ),
			array( 'coral', '#FF7F50', 'rgb' => array( 'r' => 255, 'g' => 127, 'b' => 80, ), 'hsl' => array( 'h' => 16.114, 's' => 1.000, 'l' => 0.657, ), 'hsv' => array( 'h' => 16.114, 's' => 0.686, 'v' => 1.000, ), 'cmy' => array( 'c' => 0.000, 'm' => 0.502, 'y' => 0.686, ), 'cmyk' => array( 'c' => 0.000, 'm' => 0.502, 'y' => 0.686, 'k' => 0.000, ), ),
			array( 'cornflowerblue', '#6495ED', 'rgb' => array( 'r' => 100, 'g' => 149, 'b' => 237, ), 'hsl' => array( 'h' => 218.540, 's' => 0.792, 'l' => 0.661, ), 'hsv' => array( 'h' => 218.540, 's' => 0.578, 'v' => 0.929, ), 'cmy' => array( 'c' => 0.608, 'm' => 0.416, 'y' => 0.071, ), 'cmyk' => array( 'c' => 0.578, 'm' => 0.371, 'y' => 0.000, 'k' => 0.071, ), ),
			array( 'cornsilk', '#FFF8DC', 'rgb' => array( 'r' => 255, 'g' => 248, 'b' => 220, ), 'hsl' => array( 'h' => 48.000, 's' => 1.000, 'l' => 0.931, ), 'hsv' => array( 'h' => 48.000, 's' => 0.137, 'v' => 1.000, ), 'cmy' => array( 'c' => 0.000, 'm' => 0.027, 'y' => 0.137, ), 'cmyk' => array( 'c' => 0.000, 'm' => 0.027, 'y' => 0.137, 'k' => 0.000, ), ),
			array( 'crimson', '#DC143C', 'rgb' => array( 'r' => 220, 'g' => 20, 'b' => 60, ), 'hsl' => array( 'h' => 348.000, 's' => 0.833, 'l' => 0.471, ), 'hsv' => array( 'h' => 348.000, 's' => 0.909, 'v' => 0.863, ), 'cmy' => array( 'c' => 0.137, 'm' => 0.922, 'y' => 0.765, ), 'cmyk' => array( 'c' => 0.000, 'm' => 0.909, 'y' => 0.727, 'k' => 0.137, ), ),
			array( 'cyan', '#00FFFF', 'rgb' => array( 'r' => 0, 'g' => 255, 'b' => 255, ), 'hsl' => array( 'h' => 180.000, 's' => 1.000, 'l' => 0.500, ), 'hsv' => array( 'h' => 180.000, 's' => 1.000, 'v' => 1.000, ), 'cmy' => array( 'c' => 1.000, 'm' => 0.000, 'y' => 0.000, ), 'cmyk' => array( 'c' => 1.000, 'm' => 0.000, 'y' => 0.000, 'k' => 0.000, ), ),
			array( 'darkblue', '#00008B', 'rgb' => array( 'r' => 0, 'g' => 0, 'b' => 139, ), 'hsl' => array( 'h' => 240.000, 's' => 1.000, 'l' => 0.273, ), 'hsv' => array( 'h' => 240.000, 's' => 1.000, 'v' => 0.545, ), 'cmy' => array( 'c' => 1.000, 'm' => 1.000, 'y' => 0.455, ), 'cmyk' => array( 'c' => 1.000, 'm' => 1.000, 'y' => 0.000, 'k' => 0.455, ), ),
			array( 'darkcyan', '#008B8B', 'rgb' => array( 'r' => 0, 'g' => 139, 'b' => 139, ), 'hsl' => array( 'h' => 180.000, 's' => 1.000, 'l' => 0.273, ), 'hsv' => array( 'h' => 180.000, 's' => 1.000, 'v' => 0.545, ), 'cmy' => array( 'c' => 1.000, 'm' => 0.455, 'y' => 0.455, ), 'cmyk' => array( 'c' => 1.000, 'm' => 0.000, 'y' => 0.000, 'k' => 0.455, ), ),
			array( 'darkgoldenrod', '#B8860B', 'rgb' => array( 'r' => 184, 'g' => 134, 'b' => 11, ), 'hsl' => array( 'h' => 42.659, 's' => 0.887, 'l' => 0.382, ), 'hsv' => array( 'h' => 42.659, 's' => 0.940, 'v' => 0.722, ), 'cmy' => array( 'c' => 0.278, 'm' => 0.475, 'y' => 0.957, ), 'cmyk' => array( 'c' => 0.000, 'm' => 0.272, 'y' => 0.940, 'k' => 0.278, ), ),
			array( 'darkgray', '#A9A9A9', 'rgb' => array( 'r' => 169, 'g' => 169, 'b' => 169, ), 'hsl' => array( 'h' => 0.000, 's' => 0.000, 'l' => 0.663, ), 'hsv' => array( 'h' => 0.000, 's' => 0.000, 'v' => 0.663, ), 'cmy' => array( 'c' => 0.337, 'm' => 0.337, 'y' => 0.337, ), 'cmyk' => array( 'c' => 0.000, 'm' => 0.000, 'y' => 0.000, 'k' => 0.337, ), ),
			array( 'darkgreen', '#006400', 'rgb' => array( 'r' => 0, 'g' => 100, 'b' => 0, ), 'hsl' => array( 'h' => 120.000, 's' => 1.000, 'l' => 0.196, ), 'hsv' => array( 'h' => 120.000, 's' => 1.000, 'v' => 0.392, ), 'cmy' => array( 'c' => 1.000, 'm' => 0.608, 'y' => 1.000, ), 'cmyk' => array( 'c' => 1.000, 'm' => 0.000, 'y' => 1.000, 'k' => 0.608, ), ),
			array( 'darkgrey', '#A9A9A9', 'rgb' => array( 'r' => 169, 'g' => 169, 'b' => 169, ), 'hsl' => array( 'h' => 0.000, 's' => 0.000, 'l' => 0.663, ), 'hsv' => array( 'h' => 0.000, 's' => 0.000, 'v' => 0.663, ), 'cmy' => array( 'c' => 0.337, 'm' => 0.337, 'y' => 0.337, ), 'cmyk' => array( 'c' => 0.000, 'm' => 0.000, 'y' => 0.000, 'k' => 0.337, ), ),
			array( 'darkkhaki', '#BDB76B', 'rgb' => array( 'r' => 189, 'g' => 183, 'b' => 107, ), 'hsl' => array( 'h' => 55.610, 's' => 0.383, 'l' => 0.580, ), 'hsv' => array( 'h' => 55.610, 's' => 0.434, 'v' => 0.741, ), 'cmy' => array( 'c' => 0.259, 'm' => 0.282, 'y' => 0.580, ), 'cmyk' => array( 'c' => 0.000, 'm' => 0.032, 'y' => 0.434, 'k' => 0.259, ), ),
			array( 'darkmagenta', '#8B008B', 'rgb' => array( 'r' => 139, 'g' => 0, 'b' => 139, ), 'hsl' => array( 'h' => 300.000, 's' => 1.000, 'l' => 0.273, ), 'hsv' => array( 'h' => 300.000, 's' => 1.000, 'v' => 0.545, ), 'cmy' => array( 'c' => 0.455, 'm' => 1.000, 'y' => 0.455, ), 'cmyk' => array( 'c' => 0.000, 'm' => 1.000, 'y' => 0.000, 'k' => 0.455, ), ),
			array( 'darkolivegreen', '#556B2F', 'rgb' => array( 'r' => 85, 'g' => 107, 'b' => 47, ), 'hsl' => array( 'h' => 82.000, 's' => 0.390, 'l' => 0.302, ), 'hsv' => array( 'h' => 82.000, 's' => 0.561, 'v' => 0.420, ), 'cmy' => array( 'c' => 0.667, 'm' => 0.580, 'y' => 0.816, ), 'cmyk' => array( 'c' => 0.206, 'm' => 0.000, 'y' => 0.561, 'k' => 0.580, ), ),
			array( 'darkorange', '#FF8C00', 'rgb' => array( 'r' => 255, 'g' => 140, 'b' => 0, ), 'hsl' => array( 'h' => 32.941, 's' => 1.000, 'l' => 0.500, ), 'hsv' => array( 'h' => 32.941, 's' => 1.000, 'v' => 1.000, ), 'cmy' => array( 'c' => 0.000, 'm' => 0.451, 'y' => 1.000, ), 'cmyk' => array( 'c' => 0.000, 'm' => 0.451, 'y' => 1.000, 'k' => 0.000, ), ),
			array( 'darkorchid', '#9932CC', 'rgb' => array( 'r' => 153, 'g' => 50, 'b' => 204, ), 'hsl' => array( 'h' => 280.130, 's' => 0.606, 'l' => 0.498, ), 'hsv' => array( 'h' => 280.130, 's' => 0.755, 'v' => 0.800, ), 'cmy' => array( 'c' => 0.400, 'm' => 0.804, 'y' => 0.200, ), 'cmyk' => array( 'c' => 0.250, 'm' => 0.755, 'y' => 0.000, 'k' => 0.200, ), ),
			array( 'darkred', '#8B0000', 'rgb' => array( 'r' => 139, 'g' => 0, 'b' => 0, ), 'hsl' => array( 'h' => 0.000, 's' => 1.000, 'l' => 0.273, ), 'hsv' => array( 'h' => 0.000, 's' => 1.000, 'v' => 0.545, ), 'cmy' => array( 'c' => 0.455, 'm' => 1.000, 'y' => 1.000, ), 'cmyk' => array( 'c' => 0.000, 'm' => 1.000, 'y' => 1.000, 'k' => 0.455, ), ),
			array( 'darksalmon', '#E9967A', 'rgb' => array( 'r' => 233, 'g' => 150, 'b' => 122, ), 'hsl' => array( 'h' => 15.135, 's' => 0.716, 'l' => 0.696, ), 'hsv' => array( 'h' => 15.135, 's' => 0.476, 'v' => 0.914, ), 'cmy' => array( 'c' => 0.086, 'm' => 0.412, 'y' => 0.522, ), 'cmyk' => array( 'c' => 0.000, 'm' => 0.356, 'y' => 0.476, 'k' => 0.086, ), ),
			array( 'darkseagreen', '#8FBC8F', 'rgb' => array( 'r' => 143, 'g' => 188, 'b' => 143, ), 'hsl' => array( 'h' => 120.000, 's' => 0.251, 'l' => 0.649, ), 'hsv' => array( 'h' => 120.000, 's' => 0.239, 'v' => 0.737, ), 'cmy' => array( 'c' => 0.439, 'm' => 0.263, 'y' => 0.439, ), 'cmyk' => array( 'c' => 0.239, 'm' => 0.000, 'y' => 0.239, 'k' => 0.263, ), ),
			array( 'darkslateblue', '#483D8B', 'rgb' => array( 'r' => 72, 'g' => 61, 'b' => 139, ), 'hsl' => array( 'h' => 248.462, 's' => 0.390, 'l' => 0.392, ), 'hsv' => array( 'h' => 248.462, 's' => 0.561, 'v' => 0.545, ), 'cmy' => array( 'c' => 0.718, 'm' => 0.761, 'y' => 0.455, ), 'cmyk' => array( 'c' => 0.482, 'm' => 0.561, 'y' => 0.000, 'k' => 0.455, ), ),
			array( 'darkslategray', '#2F4F4F', 'rgb' => array( 'r' => 47, 'g' => 79, 'b' => 79, ), 'hsl' => array( 'h' => 180.000, 's' => 0.254, 'l' => 0.247, ), 'hsv' => array( 'h' => 180.000, 's' => 0.405, 'v' => 0.310, ), 'cmy' => array( 'c' => 0.816, 'm' => 0.690, 'y' => 0.690, ), 'cmyk' => array( 'c' => 0.405, 'm' => 0.000, 'y' => 0.000, 'k' => 0.690, ), ),
			array( 'darkslategrey', '#2F4F4F', 'rgb' => array( 'r' => 47, 'g' => 79, 'b' => 79, ), 'hsl' => array( 'h' => 180.000, 's' => 0.254, 'l' => 0.247, ), 'hsv' => array( 'h' => 180.000, 's' => 0.405, 'v' => 0.310, ), 'cmy' => array( 'c' => 0.816, 'm' => 0.690, 'y' => 0.690, ), 'cmyk' => array( 'c' => 0.405, 'm' => 0.000, 'y' => 0.000, 'k' => 0.690, ), ),
			array( 'darkturquoise', '#00CED1', 'rgb' => array( 'r' => 0, 'g' => 206, 'b' => 209, ), 'hsl' => array( 'h' => 180.861, 's' => 1.000, 'l' => 0.410, ), 'hsv' => array( 'h' => 180.861, 's' => 1.000, 'v' => 0.820, ), 'cmy' => array( 'c' => 1.000, 'm' => 0.192, 'y' => 0.180, ), 'cmyk' => array( 'c' => 1.000, 'm' => 0.014, 'y' => 0.000, 'k' => 0.180, ), ),
			array( 'darkviolet', '#9400D3', 'rgb' => array( 'r' => 148, 'g' => 0, 'b' => 211, ), 'hsl' => array( 'h' => 282.085, 's' => 1.000, 'l' => 0.414, ), 'hsv' => array( 'h' => 282.085, 's' => 1.000, 'v' => 0.827, ), 'cmy' => array( 'c' => 0.420, 'm' => 1.000, 'y' => 0.173, ), 'cmyk' => array( 'c' => 0.299, 'm' => 1.000, 'y' => 0.000, 'k' => 0.173, ), ),
			array( 'deeppink', '#FF1493', 'rgb' => array( 'r' => 255, 'g' => 20, 'b' => 147, ), 'hsl' => array( 'h' => 327.574, 's' => 1.000, 'l' => 0.539, ), 'hsv' => array( 'h' => 327.574, 's' => 0.922, 'v' => 1.000, ), 'cmy' => array( 'c' => 0.000, 'm' => 0.922, 'y' => 0.424, ), 'cmyk' => array( 'c' => 0.000, 'm' => 0.922, 'y' => 0.424, 'k' => 0.000, ), ),
			array( 'deepskyblue', '#00BFFF', 'rgb' => array( 'r' => 0, 'g' => 191, 'b' => 255, ), 'hsl' => array( 'h' => 195.059, 's' => 1.000, 'l' => 0.500, ), 'hsv' => array( 'h' => 195.059, 's' => 1.000, 'v' => 1.000, ), 'cmy' => array( 'c' => 1.000, 'm' => 0.251, 'y' => 0.000, ), 'cmyk' => array( 'c' => 1.000, 'm' => 0.251, 'y' => 0.000, 'k' => 0.000, ), ),
			array( 'dimgray', '#696969', 'rgb' => array( 'r' => 105, 'g' => 105, 'b' => 105, ), 'hsl' => array( 'h' => 0.000, 's' => 0.000, 'l' => 0.412, ), 'hsv' => array( 'h' => 0.000, 's' => 0.000, 'v' => 0.412, ), 'cmy' => array( 'c' => 0.588, 'm' => 0.588, 'y' => 0.588, ), 'cmyk' => array( 'c' => 0.000, 'm' => 0.000, 'y' => 0.000, 'k' => 0.588, ), ),
			array( 'dimgrey', '#696969', 'rgb' => array( 'r' => 105, 'g' => 105, 'b' => 105, ), 'hsl' => array( 'h' => 0.000, 's' => 0.000, 'l' => 0.412, ), 'hsv' => array( 'h' => 0.000, 's' => 0.000, 'v' => 0.412, ), 'cmy' => array( 'c' => 0.588, 'm' => 0.588, 'y' => 0.588, ), 'cmyk' => array( 'c' => 0.000, 'm' => 0.000, 'y' => 0.000, 'k' => 0.588, ), ),
			array( 'dodgerblue', '#1E90FF', 'rgb' => array( 'r' => 30, 'g' => 144, 'b' => 255, ), 'hsl' => array( 'h' => 209.600, 's' => 1.000, 'l' => 0.559, ), 'hsv' => array( 'h' => 209.600, 's' => 0.882, 'v' => 1.000, ), 'cmy' => array( 'c' => 0.882, 'm' => 0.435, 'y' => 0.000, ), 'cmyk' => array( 'c' => 0.882, 'm' => 0.435, 'y' => 0.000, 'k' => 0.000, ), ),
			array( 'firebrick', '#B22222', 'rgb' => array( 'r' => 178, 'g' => 34, 'b' => 34, ), 'hsl' => array( 'h' => 0.000, 's' => 0.679, 'l' => 0.416, ), 'hsv' => array( 'h' => 0.000, 's' => 0.809, 'v' => 0.698, ), 'cmy' => array( 'c' => 0.302, 'm' => 0.867, 'y' => 0.867, ), 'cmyk' => array( 'c' => 0.000, 'm' => 0.809, 'y' => 0.809, 'k' => 0.302, ), ),
			array( 'floralwhite', '#FFFAF0', 'rgb' => array( 'r' => 255, 'g' => 250, 'b' => 240, ), 'hsl' => array( 'h' => 40.000, 's' => 1.000, 'l' => 0.971, ), 'hsv' => array( 'h' => 40.000, 's' => 0.059, 'v' => 1.000, ), 'cmy' => array( 'c' => 0.000, 'm' => 0.020, 'y' => 0.059, ), 'cmyk' => array( 'c' => 0.000, 'm' => 0.020, 'y' => 0.059, 'k' => 0.000, ), ),
			array( 'forestgreen', '#228B22', 'rgb' => array( 'r' => 34, 'g' => 139, 'b' => 34, ), 'hsl' => array( 'h' => 120.000, 's' => 0.607, 'l' => 0.339, ), 'hsv' => array( 'h' => 120.000, 's' => 0.755, 'v' => 0.545, ), 'cmy' => array( 'c' => 0.867, 'm' => 0.455, 'y' => 0.867, ), 'cmyk' => array( 'c' => 0.755, 'm' => 0.000, 'y' => 0.755, 'k' => 0.455, ), ),
			array( 'fuchsia', '#FF00FF', 'rgb' => array( 'r' => 255, 'g' => 0, 'b' => 255, ), 'hsl' => array( 'h' => 300.000, 's' => 1.000, 'l' => 0.500, ), 'hsv' => array( 'h' => 300.000, 's' => 1.000, 'v' => 1.000, ), 'cmy' => array( 'c' => 0.000, 'm' => 1.000, 'y' => 0.000, ), 'cmyk' => array( 'c' => 0.000, 'm' => 1.000, 'y' => 0.000, 'k' => 0.000, ), ),
			array( 'gainsboro', '#DCDCDC', 'rgb' => array( 'r' => 220, 'g' => 220, 'b' => 220, ), 'hsl' => array( 'h' => 0.000, 's' => 0.000, 'l' => 0.863, ), 'hsv' => array( 'h' => 0.000, 's' => 0.000, 'v' => 0.863, ), 'cmy' => array( 'c' => 0.137, 'm' => 0.137, 'y' => 0.137, ), 'cmyk' => array( 'c' => 0.000, 'm' => 0.000, 'y' => 0.000, 'k' => 0.137, ), ),
			array( 'ghostwhite', '#F8F8FF', 'rgb' => array( 'r' => 248, 'g' => 248, 'b' => 255, ), 'hsl' => array( 'h' => 240.000, 's' => 1.000, 'l' => 0.986, ), 'hsv' => array( 'h' => 240.000, 's' => 0.027, 'v' => 1.000, ), 'cmy' => array( 'c' => 0.027, 'm' => 0.027, 'y' => 0.000, ), 'cmyk' => array( 'c' => 0.027, 'm' => 0.027, 'y' => 0.000, 'k' => 0.000, ), ),
			array( 'gold', '#FFD700', 'rgb' => array( 'r' => 255, 'g' => 215, 'b' => 0, ), 'hsl' => array( 'h' => 50.588, 's' => 1.000, 'l' => 0.500, ), 'hsv' => array( 'h' => 50.588, 's' => 1.000, 'v' => 1.000, ), 'cmy' => array( 'c' => 0.000, 'm' => 0.157, 'y' => 1.000, ), 'cmyk' => array( 'c' => 0.000, 'm' => 0.157, 'y' => 1.000, 'k' => 0.000, ), ),
			array( 'goldenrod', '#DAA520', 'rgb' => array( 'r' => 218, 'g' => 165, 'b' => 32, ), 'hsl' => array( 'h' => 42.903, 's' => 0.744, 'l' => 0.490, ), 'hsv' => array( 'h' => 42.903, 's' => 0.853, 'v' => 0.855, ), 'cmy' => array( 'c' => 0.145, 'm' => 0.353, 'y' => 0.875, ), 'cmyk' => array( 'c' => 0.000, 'm' => 0.243, 'y' => 0.853, 'k' => 0.145, ), ),
			array( 'gray', '#808080', 'rgb' => array( 'r' => 128, 'g' => 128, 'b' => 128, ), 'hsl' => array( 'h' => 0.000, 's' => 0.000, 'l' => 0.502, ), 'hsv' => array( 'h' => 0.000, 's' => 0.000, 'v' => 0.502, ), 'cmy' => array( 'c' => 0.498, 'm' => 0.498, 'y' => 0.498, ), 'cmyk' => array( 'c' => 0.000, 'm' => 0.000, 'y' => 0.000, 'k' => 0.498, ), ),
			array( 'green', '#008000', 'rgb' => array( 'r' => 0, 'g' => 128, 'b' => 0, ), 'hsl' => array( 'h' => 120.000, 's' => 1.000, 'l' => 0.251, ), 'hsv' => array( 'h' => 120.000, 's' => 1.000, 'v' => 0.502, ), 'cmy' => array( 'c' => 1.000, 'm' => 0.498, 'y' => 1.000, ), 'cmyk' => array( 'c' => 1.000, 'm' => 0.000, 'y' => 1.000, 'k' => 0.498, ), ),
			array( 'greenyellow', '#ADFF2F', 'rgb' => array( 'r' => 173, 'g' => 255, 'b' => 47, ), 'hsl' => array( 'h' => 83.654, 's' => 1.000, 'l' => 0.592, ), 'hsv' => array( 'h' => 83.654, 's' => 0.816, 'v' => 1.000, ), 'cmy' => array( 'c' => 0.322, 'm' => 0.000, 'y' => 0.816, ), 'cmyk' => array( 'c' => 0.322, 'm' => 0.000, 'y' => 0.816, 'k' => 0.000, ), ),
			array( 'grey', '#808080', 'rgb' => array( 'r' => 128, 'g' => 128, 'b' => 128, ), 'hsl' => array( 'h' => 0.000, 's' => 0.000, 'l' => 0.502, ), 'hsv' => array( 'h' => 0.000, 's' => 0.000, 'v' => 0.502, ), 'cmy' => array( 'c' => 0.498, 'm' => 0.498, 'y' => 0.498, ), 'cmyk' => array( 'c' => 0.000, 'm' => 0.000, 'y' => 0.000, 'k' => 0.498, ), ),
			array( 'honeydew', '#F0FFF0', 'rgb' => array( 'r' => 240, 'g' => 255, 'b' => 240, ), 'hsl' => array( 'h' => 120.000, 's' => 1.000, 'l' => 0.971, ), 'hsv' => array( 'h' => 120.000, 's' => 0.059, 'v' => 1.000, ), 'cmy' => array( 'c' => 0.059, 'm' => 0.000, 'y' => 0.059, ), 'cmyk' => array( 'c' => 0.059, 'm' => 0.000, 'y' => 0.059, 'k' => 0.000, ), ),
			array( 'hotpink', '#FF69B4', 'rgb' => array( 'r' => 255, 'g' => 105, 'b' => 180, ), 'hsl' => array( 'h' => 330.000, 's' => 1.000, 'l' => 0.706, ), 'hsv' => array( 'h' => 330.000, 's' => 0.588, 'v' => 1.000, ), 'cmy' => array( 'c' => 0.000, 'm' => 0.588, 'y' => 0.294, ), 'cmyk' => array( 'c' => 0.000, 'm' => 0.588, 'y' => 0.294, 'k' => 0.000, ), ),
			array( 'indianred', '#CD5C5C', 'rgb' => array( 'r' => 205, 'g' => 92, 'b' => 92, ), 'hsl' => array( 'h' => 0.000, 's' => 0.531, 'l' => 0.582, ), 'hsv' => array( 'h' => 0.000, 's' => 0.551, 'v' => 0.804, ), 'cmy' => array( 'c' => 0.196, 'm' => 0.639, 'y' => 0.639, ), 'cmyk' => array( 'c' => 0.000, 'm' => 0.551, 'y' => 0.551, 'k' => 0.196, ), ),
			array( 'indigo', '#4B0082', 'rgb' => array( 'r' => 75, 'g' => 0, 'b' => 130, ), 'hsl' => array( 'h' => 274.615, 's' => 1.000, 'l' => 0.255, ), 'hsv' => array( 'h' => 274.615, 's' => 1.000, 'v' => 0.510, ), 'cmy' => array( 'c' => 0.706, 'm' => 1.000, 'y' => 0.490, ), 'cmyk' => array( 'c' => 0.423, 'm' => 1.000, 'y' => 0.000, 'k' => 0.490, ), ),
			array( 'ivory', '#FFFFF0', 'rgb' => array( 'r' => 255, 'g' => 255, 'b' => 240, ), 'hsl' => array( 'h' => 60.000, 's' => 1.000, 'l' => 0.971, ), 'hsv' => array( 'h' => 60.000, 's' => 0.059, 'v' => 1.000, ), 'cmy' => array( 'c' => 0.000, 'm' => 0.000, 'y' => 0.059, ), 'cmyk' => array( 'c' => 0.000, 'm' => 0.000, 'y' => 0.059, 'k' => 0.000, ), ),
			array( 'khaki', '#F0E68C', 'rgb' => array( 'r' => 240, 'g' => 230, 'b' => 140, ), 'hsl' => array( 'h' => 54.000, 's' => 0.769, 'l' => 0.745, ), 'hsv' => array( 'h' => 54.000, 's' => 0.417, 'v' => 0.941, ), 'cmy' => array( 'c' => 0.059, 'm' => 0.098, 'y' => 0.451, ), 'cmyk' => array( 'c' => 0.000, 'm' => 0.042, 'y' => 0.417, 'k' => 0.059, ), ),
			array( 'lavender', '#E6E6FA', 'rgb' => array( 'r' => 230, 'g' => 230, 'b' => 250, ), 'hsl' => array( 'h' => 240.000, 's' => 0.667, 'l' => 0.941, ), 'hsv' => array( 'h' => 240.000, 's' => 0.080, 'v' => 0.980, ), 'cmy' => array( 'c' => 0.098, 'm' => 0.098, 'y' => 0.020, ), 'cmyk' => array( 'c' => 0.080, 'm' => 0.080, 'y' => 0.000, 'k' => 0.020, ), ),
			array( 'lavenderblush', '#FFF0F5', 'rgb' => array( 'r' => 255, 'g' => 240, 'b' => 245, ), 'hsl' => array( 'h' => 340.000, 's' => 1.000, 'l' => 0.971, ), 'hsv' => array( 'h' => 340.000, 's' => 0.059, 'v' => 1.000, ), 'cmy' => array( 'c' => 0.000, 'm' => 0.059, 'y' => 0.039, ), 'cmyk' => array( 'c' => 0.000, 'm' => 0.059, 'y' => 0.039, 'k' => 0.000, ), ),
			array( 'lawngreen', '#7CFC00', 'rgb' => array( 'r' => 124, 'g' => 252, 'b' => 0, ), 'hsl' => array( 'h' => 90.476, 's' => 1.000, 'l' => 0.494, ), 'hsv' => array( 'h' => 90.476, 's' => 1.000, 'v' => 0.988, ), 'cmy' => array( 'c' => 0.514, 'm' => 0.012, 'y' => 1.000, ), 'cmyk' => array( 'c' => 0.508, 'm' => 0.000, 'y' => 1.000, 'k' => 0.012, ), ),
			array( 'lemonchiffon', '#FFFACD', 'rgb' => array( 'r' => 255, 'g' => 250, 'b' => 205, ), 'hsl' => array( 'h' => 54.000, 's' => 1.000, 'l' => 0.902, ), 'hsv' => array( 'h' => 54.000, 's' => 0.196, 'v' => 1.000, ), 'cmy' => array( 'c' => 0.000, 'm' => 0.020, 'y' => 0.196, ), 'cmyk' => array( 'c' => 0.000, 'm' => 0.020, 'y' => 0.196, 'k' => 0.000, ), ),
			array( 'lightblue', '#ADD8E6', 'rgb' => array( 'r' => 173, 'g' => 216, 'b' => 230, ), 'hsl' => array( 'h' => 194.737, 's' => 0.533, 'l' => 0.790, ), 'hsv' => array( 'h' => 194.737, 's' => 0.248, 'v' => 0.902, ), 'cmy' => array( 'c' => 0.322, 'm' => 0.153, 'y' => 0.098, ), 'cmyk' => array( 'c' => 0.248, 'm' => 0.061, 'y' => 0.000, 'k' => 0.098, ), ),
			array( 'lightcoral', '#F08080', 'rgb' => array( 'r' => 240, 'g' => 128, 'b' => 128, ), 'hsl' => array( 'h' => 0.000, 's' => 0.789, 'l' => 0.722, ), 'hsv' => array( 'h' => 0.000, 's' => 0.467, 'v' => 0.941, ), 'cmy' => array( 'c' => 0.059, 'm' => 0.498, 'y' => 0.498, ), 'cmyk' => array( 'c' => 0.000, 'm' => 0.467, 'y' => 0.467, 'k' => 0.059, ), ),
			array( 'lightcyan', '#E0FFFF', 'rgb' => array( 'r' => 224, 'g' => 255, 'b' => 255, ), 'hsl' => array( 'h' => 180.000, 's' => 1.000, 'l' => 0.939, ), 'hsv' => array( 'h' => 180.000, 's' => 0.122, 'v' => 1.000, ), 'cmy' => array( 'c' => 0.122, 'm' => 0.000, 'y' => 0.000, ), 'cmyk' => array( 'c' => 0.122, 'm' => 0.000, 'y' => 0.000, 'k' => 0.000, ), ),
			array( 'lightgoldenrodyellow', '#FAFAD2', 'rgb' => array( 'r' => 250, 'g' => 250, 'b' => 210, ), 'hsl' => array( 'h' => 60.000, 's' => 0.800, 'l' => 0.902, ), 'hsv' => array( 'h' => 60.000, 's' => 0.160, 'v' => 0.980, ), 'cmy' => array( 'c' => 0.020, 'm' => 0.020, 'y' => 0.176, ), 'cmyk' => array( 'c' => 0.000, 'm' => 0.000, 'y' => 0.160, 'k' => 0.020, ), ),
			array( 'lightgray', '#D3D3D3', 'rgb' => array( 'r' => 211, 'g' => 211, 'b' => 211, ), 'hsl' => array( 'h' => 0.000, 's' => 0.000, 'l' => 0.827, ), 'hsv' => array( 'h' => 0.000, 's' => 0.000, 'v' => 0.827, ), 'cmy' => array( 'c' => 0.173, 'm' => 0.173, 'y' => 0.173, ), 'cmyk' => array( 'c' => 0.000, 'm' => 0.000, 'y' => 0.000, 'k' => 0.173, ), ),
			array( 'lightgreen', '#90EE90', 'rgb' => array( 'r' => 144, 'g' => 238, 'b' => 144, ), 'hsl' => array( 'h' => 120.000, 's' => 0.734, 'l' => 0.749, ), 'hsv' => array( 'h' => 120.000, 's' => 0.395, 'v' => 0.933, ), 'cmy' => array( 'c' => 0.435, 'm' => 0.067, 'y' => 0.435, ), 'cmyk' => array( 'c' => 0.395, 'm' => 0.000, 'y' => 0.395, 'k' => 0.067, ), ),
			array( 'lightgrey', '#D3D3D3', 'rgb' => array( 'r' => 211, 'g' => 211, 'b' => 211, ), 'hsl' => array( 'h' => 0.000, 's' => 0.000, 'l' => 0.827, ), 'hsv' => array( 'h' => 0.000, 's' => 0.000, 'v' => 0.827, ), 'cmy' => array( 'c' => 0.173, 'm' => 0.173, 'y' => 0.173, ), 'cmyk' => array( 'c' => 0.000, 'm' => 0.000, 'y' => 0.000, 'k' => 0.173, ), ),
			array( 'lightpink', '#FFB6C1', 'rgb' => array( 'r' => 255, 'g' => 182, 'b' => 193, ), 'hsl' => array( 'h' => 350.959, 's' => 1.000, 'l' => 0.857, ), 'hsv' => array( 'h' => 350.959, 's' => 0.286, 'v' => 1.000, ), 'cmy' => array( 'c' => 0.000, 'm' => 0.286, 'y' => 0.243, ), 'cmyk' => array( 'c' => 0.000, 'm' => 0.286, 'y' => 0.243, 'k' => 0.000, ), ),
			array( 'lightsalmon', '#FFA07A', 'rgb' => array( 'r' => 255, 'g' => 160, 'b' => 122, ), 'hsl' => array( 'h' => 17.143, 's' => 1.000, 'l' => 0.739, ), 'hsv' => array( 'h' => 17.143, 's' => 0.522, 'v' => 1.000, ), 'cmy' => array( 'c' => 0.000, 'm' => 0.373, 'y' => 0.522, ), 'cmyk' => array( 'c' => 0.000, 'm' => 0.373, 'y' => 0.522, 'k' => 0.000, ), ),
			array( 'lightseagreen', '#20B2AA', 'rgb' => array( 'r' => 32, 'g' => 178, 'b' => 170, ), 'hsl' => array( 'h' => 176.712, 's' => 0.695, 'l' => 0.412, ), 'hsv' => array( 'h' => 176.712, 's' => 0.820, 'v' => 0.698, ), 'cmy' => array( 'c' => 0.875, 'm' => 0.302, 'y' => 0.333, ), 'cmyk' => array( 'c' => 0.820, 'm' => 0.000, 'y' => 0.045, 'k' => 0.302, ), ),
			array( 'lightskyblue', '#87CEFA', 'rgb' => array( 'r' => 135, 'g' => 206, 'b' => 250, ), 'hsl' => array( 'h' => 202.957, 's' => 0.920, 'l' => 0.755, ), 'hsv' => array( 'h' => 202.957, 's' => 0.460, 'v' => 0.980, ), 'cmy' => array( 'c' => 0.471, 'm' => 0.192, 'y' => 0.020, ), 'cmyk' => array( 'c' => 0.460, 'm' => 0.176, 'y' => 0.000, 'k' => 0.020, ), ),
			array( 'lightslategray', '#778899', 'rgb' => array( 'r' => 119, 'g' => 136, 'b' => 153, ), 'hsl' => array( 'h' => 210.000, 's' => 0.143, 'l' => 0.533, ), 'hsv' => array( 'h' => 210.000, 's' => 0.222, 'v' => 0.600, ), 'cmy' => array( 'c' => 0.533, 'm' => 0.467, 'y' => 0.400, ), 'cmyk' => array( 'c' => 0.222, 'm' => 0.111, 'y' => 0.000, 'k' => 0.400, ), ),
			array( 'lightslategrey', '#778899', 'rgb' => array( 'r' => 119, 'g' => 136, 'b' => 153, ), 'hsl' => array( 'h' => 210.000, 's' => 0.143, 'l' => 0.533, ), 'hsv' => array( 'h' => 210.000, 's' => 0.222, 'v' => 0.600, ), 'cmy' => array( 'c' => 0.533, 'm' => 0.467, 'y' => 0.400, ), 'cmyk' => array( 'c' => 0.222, 'm' => 0.111, 'y' => 0.000, 'k' => 0.400, ), ),
			array( 'lightsteelblue', '#B0C4DE', 'rgb' => array( 'r' => 176, 'g' => 196, 'b' => 222, ), 'hsl' => array( 'h' => 213.913, 's' => 0.411, 'l' => 0.780, ), 'hsv' => array( 'h' => 213.913, 's' => 0.207, 'v' => 0.871, ), 'cmy' => array( 'c' => 0.310, 'm' => 0.231, 'y' => 0.129, ), 'cmyk' => array( 'c' => 0.207, 'm' => 0.117, 'y' => 0.000, 'k' => 0.129, ), ),
			array( 'lightyellow', '#FFFFE0', 'rgb' => array( 'r' => 255, 'g' => 255, 'b' => 224, ), 'hsl' => array( 'h' => 60.000, 's' => 1.000, 'l' => 0.939, ), 'hsv' => array( 'h' => 60.000, 's' => 0.122, 'v' => 1.000, ), 'cmy' => array( 'c' => 0.000, 'm' => 0.000, 'y' => 0.122, ), 'cmyk' => array( 'c' => 0.000, 'm' => 0.000, 'y' => 0.122, 'k' => 0.000, ), ),
			array( 'lime', '#00FF00', 'rgb' => array( 'r' => 0, 'g' => 255, 'b' => 0, ), 'hsl' => array( 'h' => 120.000, 's' => 1.000, 'l' => 0.500, ), 'hsv' => array( 'h' => 120.000, 's' => 1.000, 'v' => 1.000, ), 'cmy' => array( 'c' => 1.000, 'm' => 0.000, 'y' => 1.000, ), 'cmyk' => array( 'c' => 1.000, 'm' => 0.000, 'y' => 1.000, 'k' => 0.000, ), ),
			array( 'limegreen', '#32CD32', 'rgb' => array( 'r' => 50, 'g' => 205, 'b' => 50, ), 'hsl' => array( 'h' => 120.000, 's' => 0.608, 'l' => 0.500, ), 'hsv' => array( 'h' => 120.000, 's' => 0.756, 'v' => 0.804, ), 'cmy' => array( 'c' => 0.804, 'm' => 0.196, 'y' => 0.804, ), 'cmyk' => array( 'c' => 0.756, 'm' => 0.000, 'y' => 0.756, 'k' => 0.196, ), ),
			array( 'linen', '#FAF0E6', 'rgb' => array( 'r' => 250, 'g' => 240, 'b' => 230, ), 'hsl' => array( 'h' => 30.000, 's' => 0.667, 'l' => 0.941, ), 'hsv' => array( 'h' => 30.000, 's' => 0.080, 'v' => 0.980, ), 'cmy' => array( 'c' => 0.020, 'm' => 0.059, 'y' => 0.098, ), 'cmyk' => array( 'c' => 0.000, 'm' => 0.040, 'y' => 0.080, 'k' => 0.020, ), ),
			array( 'magenta', '#FF00FF', 'rgb' => array( 'r' => 255, 'g' => 0, 'b' => 255, ), 'hsl' => array( 'h' => 300.000, 's' => 1.000, 'l' => 0.500, ), 'hsv' => array( 'h' => 300.000, 's' => 1.000, 'v' => 1.000, ), 'cmy' => array( 'c' => 0.000, 'm' => 1.000, 'y' => 0.000, ), 'cmyk' => array( 'c' => 0.000, 'm' => 1.000, 'y' => 0.000, 'k' => 0.000, ), ),
			array( 'maroon', '#800000', 'rgb' => array( 'r' => 128, 'g' => 0, 'b' => 0, ), 'hsl' => array( 'h' => 0.000, 's' => 1.000, 'l' => 0.251, ), 'hsv' => array( 'h' => 0.000, 's' => 1.000, 'v' => 0.502, ), 'cmy' => array( 'c' => 0.498, 'm' => 1.000, 'y' => 1.000, ), 'cmyk' => array( 'c' => 0.000, 'm' => 1.000, 'y' => 1.000, 'k' => 0.498, ), ),
			array( 'mediumaquamarine', '#66CDAA', 'rgb' => array( 'r' => 102, 'g' => 205, 'b' => 170, ), 'hsl' => array( 'h' => 159.612, 's' => 0.507, 'l' => 0.602, ), 'hsv' => array( 'h' => 159.612, 's' => 0.502, 'v' => 0.804, ), 'cmy' => array( 'c' => 0.600, 'm' => 0.196, 'y' => 0.333, ), 'cmyk' => array( 'c' => 0.502, 'm' => 0.000, 'y' => 0.171, 'k' => 0.196, ), ),
			array( 'mediumblue', '#0000CD', 'rgb' => array( 'r' => 0, 'g' => 0, 'b' => 205, ), 'hsl' => array( 'h' => 240.000, 's' => 1.000, 'l' => 0.402, ), 'hsv' => array( 'h' => 240.000, 's' => 1.000, 'v' => 0.804, ), 'cmy' => array( 'c' => 1.000, 'm' => 1.000, 'y' => 0.196, ), 'cmyk' => array( 'c' => 1.000, 'm' => 1.000, 'y' => 0.000, 'k' => 0.196, ), ),
			array( 'mediumorchid', '#BA55D3', 'rgb' => array( 'r' => 186, 'g' => 85, 'b' => 211, ), 'hsl' => array( 'h' => 288.095, 's' => 0.589, 'l' => 0.580, ), 'hsv' => array( 'h' => 288.095, 's' => 0.597, 'v' => 0.827, ), 'cmy' => array( 'c' => 0.271, 'm' => 0.667, 'y' => 0.173, ), 'cmyk' => array( 'c' => 0.118, 'm' => 0.597, 'y' => 0.000, 'k' => 0.173, ), ),
			array( 'mediumpurple', '#9370DB', 'rgb' => array( 'r' => 147, 'g' => 112, 'b' => 219, ), 'hsl' => array( 'h' => 259.626, 's' => 0.598, 'l' => 0.649, ), 'hsv' => array( 'h' => 259.626, 's' => 0.489, 'v' => 0.859, ), 'cmy' => array( 'c' => 0.424, 'm' => 0.561, 'y' => 0.141, ), 'cmyk' => array( 'c' => 0.329, 'm' => 0.489, 'y' => 0.000, 'k' => 0.141, ), ),
			array( 'mediumseagreen', '#3CB371', 'rgb' => array( 'r' => 60, 'g' => 179, 'b' => 113, ), 'hsl' => array( 'h' => 146.723, 's' => 0.498, 'l' => 0.469, ), 'hsv' => array( 'h' => 146.723, 's' => 0.665, 'v' => 0.702, ), 'cmy' => array( 'c' => 0.765, 'm' => 0.298, 'y' => 0.557, ), 'cmyk' => array( 'c' => 0.665, 'm' => 0.000, 'y' => 0.369, 'k' => 0.298, ), ),
			array( 'mediumslateblue', '#7B68EE', 'rgb' => array( 'r' => 123, 'g' => 104, 'b' => 238, ), 'hsl' => array( 'h' => 248.507, 's' => 0.798, 'l' => 0.671, ), 'hsv' => array( 'h' => 248.507, 's' => 0.563, 'v' => 0.933, ), 'cmy' => array( 'c' => 0.518, 'm' => 0.592, 'y' => 0.067, ), 'cmyk' => array( 'c' => 0.483, 'm' => 0.563, 'y' => 0.000, 'k' => 0.067, ), ),
			array( 'mediumspringgreen', '#00FA9A', 'rgb' => array( 'r' => 0, 'g' => 250, 'b' => 154, ), 'hsl' => array( 'h' => 156.960, 's' => 1.000, 'l' => 0.490, ), 'hsv' => array( 'h' => 156.960, 's' => 1.000, 'v' => 0.980, ), 'cmy' => array( 'c' => 1.000, 'm' => 0.020, 'y' => 0.396, ), 'cmyk' => array( 'c' => 1.000, 'm' => 0.000, 'y' => 0.384, 'k' => 0.020, ), ),
			array( 'mediumturquoise', '#48D1CC', 'rgb' => array( 'r' => 72, 'g' => 209, 'b' => 204, ), 'hsl' => array( 'h' => 177.810, 's' => 0.598, 'l' => 0.551, ), 'hsv' => array( 'h' => 177.810, 's' => 0.656, 'v' => 0.820, ), 'cmy' => array( 'c' => 0.718, 'm' => 0.180, 'y' => 0.200, ), 'cmyk' => array( 'c' => 0.656, 'm' => 0.000, 'y' => 0.024, 'k' => 0.180, ), ),
			array( 'mediumvioletred', '#C71585', 'rgb' => array( 'r' => 199, 'g' => 21, 'b' => 133, ), 'hsl' => array( 'h' => 322.247, 's' => 0.809, 'l' => 0.431, ), 'hsv' => array( 'h' => 322.247, 's' => 0.894, 'v' => 0.780, ), 'cmy' => array( 'c' => 0.220, 'm' => 0.918, 'y' => 0.478, ), 'cmyk' => array( 'c' => 0.000, 'm' => 0.894, 'y' => 0.332, 'k' => 0.220, ), ),
			array( 'midnightblue', '#191970', 'rgb' => array( 'r' => 25, 'g' => 25, 'b' => 112, ), 'hsl' => array( 'h' => 240.000, 's' => 0.635, 'l' => 0.269, ), 'hsv' => array( 'h' => 240.000, 's' => 0.777, 'v' => 0.439, ), 'cmy' => array( 'c' => 0.902, 'm' => 0.902, 'y' => 0.561, ), 'cmyk' => array( 'c' => 0.777, 'm' => 0.777, 'y' => 0.000, 'k' => 0.561, ), ),
			array( 'mintcream', '#F5FFFA', 'rgb' => array( 'r' => 245, 'g' => 255, 'b' => 250, ), 'hsl' => array( 'h' => 150.000, 's' => 1.000, 'l' => 0.980, ), 'hsv' => array( 'h' => 150.000, 's' => 0.039, 'v' => 1.000, ), 'cmy' => array( 'c' => 0.039, 'm' => 0.000, 'y' => 0.020, ), 'cmyk' => array( 'c' => 0.039, 'm' => 0.000, 'y' => 0.020, 'k' => 0.000, ), ),
			array( 'mistyrose', '#FFE4E1', 'rgb' => array( 'r' => 255, 'g' => 228, 'b' => 225, ), 'hsl' => array( 'h' => 6.000, 's' => 1.000, 'l' => 0.941, ), 'hsv' => array( 'h' => 6.000, 's' => 0.118, 'v' => 1.000, ), 'cmy' => array( 'c' => 0.000, 'm' => 0.106, 'y' => 0.118, ), 'cmyk' => array( 'c' => 0.000, 'm' => 0.106, 'y' => 0.118, 'k' => 0.000, ), ),
			array( 'moccasin', '#FFE4B5', 'rgb' => array( 'r' => 255, 'g' => 228, 'b' => 181, ), 'hsl' => array( 'h' => 38.108, 's' => 1.000, 'l' => 0.855, ), 'hsv' => array( 'h' => 38.108, 's' => 0.290, 'v' => 1.000, ), 'cmy' => array( 'c' => 0.000, 'm' => 0.106, 'y' => 0.290, ), 'cmyk' => array( 'c' => 0.000, 'm' => 0.106, 'y' => 0.290, 'k' => 0.000, ), ),
			array( 'navajowhite', '#FFDEAD', 'rgb' => array( 'r' => 255, 'g' => 222, 'b' => 173, ), 'hsl' => array( 'h' => 35.854, 's' => 1.000, 'l' => 0.839, ), 'hsv' => array( 'h' => 35.854, 's' => 0.322, 'v' => 1.000, ), 'cmy' => array( 'c' => 0.000, 'm' => 0.129, 'y' => 0.322, ), 'cmyk' => array( 'c' => 0.000, 'm' => 0.129, 'y' => 0.322, 'k' => 0.000, ), ),
			array( 'navy', '#000080', 'rgb' => array( 'r' => 0, 'g' => 0, 'b' => 128, ), 'hsl' => array( 'h' => 240.000, 's' => 1.000, 'l' => 0.251, ), 'hsv' => array( 'h' => 240.000, 's' => 1.000, 'v' => 0.502, ), 'cmy' => array( 'c' => 1.000, 'm' => 1.000, 'y' => 0.498, ), 'cmyk' => array( 'c' => 1.000, 'm' => 1.000, 'y' => 0.000, 'k' => 0.498, ), ),
			array( 'oldlace', '#FDF5E6', 'rgb' => array( 'r' => 253, 'g' => 245, 'b' => 230, ), 'hsl' => array( 'h' => 39.130, 's' => 0.852, 'l' => 0.947, ), 'hsv' => array( 'h' => 39.130, 's' => 0.091, 'v' => 0.992, ), 'cmy' => array( 'c' => 0.008, 'm' => 0.039, 'y' => 0.098, ), 'cmyk' => array( 'c' => 0.000, 'm' => 0.032, 'y' => 0.091, 'k' => 0.008, ), ),
			array( 'olive', '#808000', 'rgb' => array( 'r' => 128, 'g' => 128, 'b' => 0, ), 'hsl' => array( 'h' => 60.000, 's' => 1.000, 'l' => 0.251, ), 'hsv' => array( 'h' => 60.000, 's' => 1.000, 'v' => 0.502, ), 'cmy' => array( 'c' => 0.498, 'm' => 0.498, 'y' => 1.000, ), 'cmyk' => array( 'c' => 0.000, 'm' => 0.000, 'y' => 1.000, 'k' => 0.498, ), ),
			array( 'olivedrab', '#6B8E23', 'rgb' => array( 'r' => 107, 'g' => 142, 'b' => 35, ), 'hsl' => array( 'h' => 79.626, 's' => 0.605, 'l' => 0.347, ), 'hsv' => array( 'h' => 79.626, 's' => 0.754, 'v' => 0.557, ), 'cmy' => array( 'c' => 0.580, 'm' => 0.443, 'y' => 0.863, ), 'cmyk' => array( 'c' => 0.246, 'm' => 0.000, 'y' => 0.754, 'k' => 0.443, ), ),
			array( 'orange', '#FFA500', 'rgb' => array( 'r' => 255, 'g' => 165, 'b' => 0, ), 'hsl' => array( 'h' => 38.824, 's' => 1.000, 'l' => 0.500, ), 'hsv' => array( 'h' => 38.824, 's' => 1.000, 'v' => 1.000, ), 'cmy' => array( 'c' => 0.000, 'm' => 0.353, 'y' => 1.000, ), 'cmyk' => array( 'c' => 0.000, 'm' => 0.353, 'y' => 1.000, 'k' => 0.000, ), ),
			array( 'orangered', '#FF4500', 'rgb' => array( 'r' => 255, 'g' => 69, 'b' => 0, ), 'hsl' => array( 'h' => 16.235, 's' => 1.000, 'l' => 0.500, ), 'hsv' => array( 'h' => 16.235, 's' => 1.000, 'v' => 1.000, ), 'cmy' => array( 'c' => 0.000, 'm' => 0.729, 'y' => 1.000, ), 'cmyk' => array( 'c' => 0.000, 'm' => 0.729, 'y' => 1.000, 'k' => 0.000, ), ),
			array( 'orchid', '#DA70D6', 'rgb' => array( 'r' => 218, 'g' => 112, 'b' => 214, ), 'hsl' => array( 'h' => 302.264, 's' => 0.589, 'l' => 0.647, ), 'hsv' => array( 'h' => 302.264, 's' => 0.486, 'v' => 0.855, ), 'cmy' => array( 'c' => 0.145, 'm' => 0.561, 'y' => 0.161, ), 'cmyk' => array( 'c' => 0.000, 'm' => 0.486, 'y' => 0.018, 'k' => 0.145, ), ),
			array( 'palegoldenrod', '#EEE8AA', 'rgb' => array( 'r' => 238, 'g' => 232, 'b' => 170, ), 'hsl' => array( 'h' => 54.706, 's' => 0.667, 'l' => 0.800, ), 'hsv' => array( 'h' => 54.706, 's' => 0.286, 'v' => 0.933, ), 'cmy' => array( 'c' => 0.067, 'm' => 0.090, 'y' => 0.333, ), 'cmyk' => array( 'c' => 0.000, 'm' => 0.025, 'y' => 0.286, 'k' => 0.067, ), ),
			array( 'palegreen', '#98FB98', 'rgb' => array( 'r' => 152, 'g' => 251, 'b' => 152, ), 'hsl' => array( 'h' => 120.000, 's' => 0.925, 'l' => 0.790, ), 'hsv' => array( 'h' => 120.000, 's' => 0.394, 'v' => 0.984, ), 'cmy' => array( 'c' => 0.404, 'm' => 0.016, 'y' => 0.404, ), 'cmyk' => array( 'c' => 0.394, 'm' => 0.000, 'y' => 0.394, 'k' => 0.016, ), ),
			array( 'paleturquoise', '#AFEEEE', 'rgb' => array( 'r' => 175, 'g' => 238, 'b' => 238, ), 'hsl' => array( 'h' => 180.000, 's' => 0.649, 'l' => 0.810, ), 'hsv' => array( 'h' => 180.000, 's' => 0.265, 'v' => 0.933, ), 'cmy' => array( 'c' => 0.314, 'm' => 0.067, 'y' => 0.067, ), 'cmyk' => array( 'c' => 0.265, 'm' => 0.000, 'y' => 0.000, 'k' => 0.067, ), ),
			array( 'palevioletred', '#DB7093', 'rgb' => array( 'r' => 219, 'g' => 112, 'b' => 147, ), 'hsl' => array( 'h' => 340.374, 's' => 0.598, 'l' => 0.649, ), 'hsv' => array( 'h' => 340.374, 's' => 0.489, 'v' => 0.859, ), 'cmy' => array( 'c' => 0.141, 'm' => 0.561, 'y' => 0.424, ), 'cmyk' => array( 'c' => 0.000, 'm' => 0.489, 'y' => 0.329, 'k' => 0.141, ), ),
			array( 'papayawhip', '#FFEFD5', 'rgb' => array( 'r' => 255, 'g' => 239, 'b' => 213, ), 'hsl' => array( 'h' => 37.143, 's' => 1.000, 'l' => 0.918, ), 'hsv' => array( 'h' => 37.143, 's' => 0.165, 'v' => 1.000, ), 'cmy' => array( 'c' => 0.000, 'm' => 0.063, 'y' => 0.165, ), 'cmyk' => array( 'c' => 0.000, 'm' => 0.063, 'y' => 0.165, 'k' => 0.000, ), ),
			array( 'peachpuff', '#FFDAB9', 'rgb' => array( 'r' => 255, 'g' => 218, 'b' => 185, ), 'hsl' => array( 'h' => 28.286, 's' => 1.000, 'l' => 0.863, ), 'hsv' => array( 'h' => 28.286, 's' => 0.275, 'v' => 1.000, ), 'cmy' => array( 'c' => 0.000, 'm' => 0.145, 'y' => 0.275, ), 'cmyk' => array( 'c' => 0.000, 'm' => 0.145, 'y' => 0.275, 'k' => 0.000, ), ),
			array( 'peru', '#CD853F', 'rgb' => array( 'r' => 205, 'g' => 133, 'b' => 63, ), 'hsl' => array( 'h' => 29.577, 's' => 0.587, 'l' => 0.525, ), 'hsv' => array( 'h' => 29.577, 's' => 0.693, 'v' => 0.804, ), 'cmy' => array( 'c' => 0.196, 'm' => 0.478, 'y' => 0.753, ), 'cmyk' => array( 'c' => 0.000, 'm' => 0.351, 'y' => 0.693, 'k' => 0.196, ), ),
			array( 'pink', '#FFC0CB', 'rgb' => array( 'r' => 255, 'g' => 192, 'b' => 203, ), 'hsl' => array( 'h' => 349.524, 's' => 1.000, 'l' => 0.876, ), 'hsv' => array( 'h' => 349.524, 's' => 0.247, 'v' => 1.000, ), 'cmy' => array( 'c' => 0.000, 'm' => 0.247, 'y' => 0.204, ), 'cmyk' => array( 'c' => 0.000, 'm' => 0.247, 'y' => 0.204, 'k' => 0.000, ), ),
			array( 'plum', '#DDA0DD', 'rgb' => array( 'r' => 221, 'g' => 160, 'b' => 221, ), 'hsl' => array( 'h' => 300.000, 's' => 0.473, 'l' => 0.747, ), 'hsv' => array( 'h' => 300.000, 's' => 0.276, 'v' => 0.867, ), 'cmy' => array( 'c' => 0.133, 'm' => 0.373, 'y' => 0.133, ), 'cmyk' => array( 'c' => 0.000, 'm' => 0.276, 'y' => 0.000, 'k' => 0.133, ), ),
			array( 'powderblue', '#B0E0E6', 'rgb' => array( 'r' => 176, 'g' => 224, 'b' => 230, ), 'hsl' => array( 'h' => 186.667, 's' => 0.519, 'l' => 0.796, ), 'hsv' => array( 'h' => 186.667, 's' => 0.235, 'v' => 0.902, ), 'cmy' => array( 'c' => 0.310, 'm' => 0.122, 'y' => 0.098, ), 'cmyk' => array( 'c' => 0.235, 'm' => 0.026, 'y' => 0.000, 'k' => 0.098, ), ),
			array( 'purple', '#800080', 'rgb' => array( 'r' => 128, 'g' => 0, 'b' => 128, ), 'hsl' => array( 'h' => 300.000, 's' => 1.000, 'l' => 0.251, ), 'hsv' => array( 'h' => 300.000, 's' => 1.000, 'v' => 0.502, ), 'cmy' => array( 'c' => 0.498, 'm' => 1.000, 'y' => 0.498, ), 'cmyk' => array( 'c' => 0.000, 'm' => 1.000, 'y' => 0.000, 'k' => 0.498, ), ),
			array( 'red', '#FF0000', 'rgb' => array( 'r' => 255, 'g' => 0, 'b' => 0, ), 'hsl' => array( 'h' => 0.000, 's' => 1.000, 'l' => 0.500, ), 'hsv' => array( 'h' => 0.000, 's' => 1.000, 'v' => 1.000, ), 'cmy' => array( 'c' => 0.000, 'm' => 1.000, 'y' => 1.000, ), 'cmyk' => array( 'c' => 0.000, 'm' => 1.000, 'y' => 1.000, 'k' => 0.000, ), ),
			array( 'rosybrown', '#BC8F8F', 'rgb' => array( 'r' => 188, 'g' => 143, 'b' => 143, ), 'hsl' => array( 'h' => 0.000, 's' => 0.251, 'l' => 0.649, ), 'hsv' => array( 'h' => 0.000, 's' => 0.239, 'v' => 0.737, ), 'cmy' => array( 'c' => 0.263, 'm' => 0.439, 'y' => 0.439, ), 'cmyk' => array( 'c' => 0.000, 'm' => 0.239, 'y' => 0.239, 'k' => 0.263, ), ),
			array( 'royalblue', '#4169E1', 'rgb' => array( 'r' => 65, 'g' => 105, 'b' => 225, ), 'hsl' => array( 'h' => 225.000, 's' => 0.727, 'l' => 0.569, ), 'hsv' => array( 'h' => 225.000, 's' => 0.711, 'v' => 0.882, ), 'cmy' => array( 'c' => 0.745, 'm' => 0.588, 'y' => 0.118, ), 'cmyk' => array( 'c' => 0.711, 'm' => 0.533, 'y' => 0.000, 'k' => 0.118, ), ),
			array( 'saddlebrown', '#8B4513', 'rgb' => array( 'r' => 139, 'g' => 69, 'b' => 19, ), 'hsl' => array( 'h' => 25.000, 's' => 0.759, 'l' => 0.310, ), 'hsv' => array( 'h' => 25.000, 's' => 0.863, 'v' => 0.545, ), 'cmy' => array( 'c' => 0.455, 'm' => 0.729, 'y' => 0.925, ), 'cmyk' => array( 'c' => 0.000, 'm' => 0.504, 'y' => 0.863, 'k' => 0.455, ), ),
			array( 'salmon', '#FA8072', 'rgb' => array( 'r' => 250, 'g' => 128, 'b' => 114, ), 'hsl' => array( 'h' => 6.176, 's' => 0.932, 'l' => 0.714, ), 'hsv' => array( 'h' => 6.176, 's' => 0.544, 'v' => 0.980, ), 'cmy' => array( 'c' => 0.020, 'm' => 0.498, 'y' => 0.553, ), 'cmyk' => array( 'c' => 0.000, 'm' => 0.488, 'y' => 0.544, 'k' => 0.020, ), ),
			array( 'sandybrown', '#F4A460', 'rgb' => array( 'r' => 244, 'g' => 164, 'b' => 96, ), 'hsl' => array( 'h' => 27.568, 's' => 0.871, 'l' => 0.667, ), 'hsv' => array( 'h' => 27.568, 's' => 0.607, 'v' => 0.957, ), 'cmy' => array( 'c' => 0.043, 'm' => 0.357, 'y' => 0.624, ), 'cmyk' => array( 'c' => 0.000, 'm' => 0.328, 'y' => 0.607, 'k' => 0.043, ), ),
			array( 'seagreen', '#2E8B57', 'rgb' => array( 'r' => 46, 'g' => 139, 'b' => 87, ), 'hsl' => array( 'h' => 146.452, 's' => 0.503, 'l' => 0.363, ), 'hsv' => array( 'h' => 146.452, 's' => 0.669, 'v' => 0.545, ), 'cmy' => array( 'c' => 0.820, 'm' => 0.455, 'y' => 0.659, ), 'cmyk' => array( 'c' => 0.669, 'm' => 0.000, 'y' => 0.374, 'k' => 0.455, ), ),
			array( 'seashell', '#FFF5EE', 'rgb' => array( 'r' => 255, 'g' => 245, 'b' => 238, ), 'hsl' => array( 'h' => 24.706, 's' => 1.000, 'l' => 0.967, ), 'hsv' => array( 'h' => 24.706, 's' => 0.067, 'v' => 1.000, ), 'cmy' => array( 'c' => 0.000, 'm' => 0.039, 'y' => 0.067, ), 'cmyk' => array( 'c' => 0.000, 'm' => 0.039, 'y' => 0.067, 'k' => 0.000, ), ),
			array( 'sienna', '#A0522D', 'rgb' => array( 'r' => 160, 'g' => 82, 'b' => 45, ), 'hsl' => array( 'h' => 19.304, 's' => 0.561, 'l' => 0.402, ), 'hsv' => array( 'h' => 19.304, 's' => 0.719, 'v' => 0.627, ), 'cmy' => array( 'c' => 0.373, 'm' => 0.678, 'y' => 0.824, ), 'cmyk' => array( 'c' => 0.000, 'm' => 0.488, 'y' => 0.719, 'k' => 0.373, ), ),
			array( 'silver', '#C0C0C0', 'rgb' => array( 'r' => 192, 'g' => 192, 'b' => 192, ), 'hsl' => array( 'h' => 0.000, 's' => 0.000, 'l' => 0.753, ), 'hsv' => array( 'h' => 0.000, 's' => 0.000, 'v' => 0.753, ), 'cmy' => array( 'c' => 0.247, 'm' => 0.247, 'y' => 0.247, ), 'cmyk' => array( 'c' => 0.000, 'm' => 0.000, 'y' => 0.000, 'k' => 0.247, ), ),
			array( 'skyblue', '#87CEEB', 'rgb' => array( 'r' => 135, 'g' => 206, 'b' => 235, ), 'hsl' => array( 'h' => 197.400, 's' => 0.714, 'l' => 0.725, ), 'hsv' => array( 'h' => 197.400, 's' => 0.426, 'v' => 0.922, ), 'cmy' => array( 'c' => 0.471, 'm' => 0.192, 'y' => 0.078, ), 'cmyk' => array( 'c' => 0.426, 'm' => 0.123, 'y' => 0.000, 'k' => 0.078, ), ),
			array( 'slateblue', '#6A5ACD', 'rgb' => array( 'r' => 106, 'g' => 90, 'b' => 205, ), 'hsl' => array( 'h' => 248.348, 's' => 0.535, 'l' => 0.578, ), 'hsv' => array( 'h' => 248.348, 's' => 0.561, 'v' => 0.804, ), 'cmy' => array( 'c' => 0.584, 'm' => 0.647, 'y' => 0.196, ), 'cmyk' => array( 'c' => 0.483, 'm' => 0.561, 'y' => 0.000, 'k' => 0.196, ), ),
			array( 'slategray', '#708090', 'rgb' => array( 'r' => 112, 'g' => 128, 'b' => 144, ), 'hsl' => array( 'h' => 210.000, 's' => 0.126, 'l' => 0.502, ), 'hsv' => array( 'h' => 210.000, 's' => 0.222, 'v' => 0.565, ), 'cmy' => array( 'c' => 0.561, 'm' => 0.498, 'y' => 0.435, ), 'cmyk' => array( 'c' => 0.222, 'm' => 0.111, 'y' => 0.000, 'k' => 0.435, ), ),
			array( 'slategrey', '#708090', 'rgb' => array( 'r' => 112, 'g' => 128, 'b' => 144, ), 'hsl' => array( 'h' => 210.000, 's' => 0.126, 'l' => 0.502, ), 'hsv' => array( 'h' => 210.000, 's' => 0.222, 'v' => 0.565, ), 'cmy' => array( 'c' => 0.561, 'm' => 0.498, 'y' => 0.435, ), 'cmyk' => array( 'c' => 0.222, 'm' => 0.111, 'y' => 0.000, 'k' => 0.435, ), ),
			array( 'snow', '#FFFAFA', 'rgb' => array( 'r' => 255, 'g' => 250, 'b' => 250, ), 'hsl' => array( 'h' => 0.000, 's' => 1.000, 'l' => 0.990, ), 'hsv' => array( 'h' => 0.000, 's' => 0.020, 'v' => 1.000, ), 'cmy' => array( 'c' => 0.000, 'm' => 0.020, 'y' => 0.020, ), 'cmyk' => array( 'c' => 0.000, 'm' => 0.020, 'y' => 0.020, 'k' => 0.000, ), ),
			array( 'springgreen', '#00FF7F', 'rgb' => array( 'r' => 0, 'g' => 255, 'b' => 127, ), 'hsl' => array( 'h' => 149.882, 's' => 1.000, 'l' => 0.500, ), 'hsv' => array( 'h' => 149.882, 's' => 1.000, 'v' => 1.000, ), 'cmy' => array( 'c' => 1.000, 'm' => 0.000, 'y' => 0.502, ), 'cmyk' => array( 'c' => 1.000, 'm' => 0.000, 'y' => 0.502, 'k' => 0.000, ), ),
			array( 'steelblue', '#4682B4', 'rgb' => array( 'r' => 70, 'g' => 130, 'b' => 180, ), 'hsl' => array( 'h' => 207.273, 's' => 0.440, 'l' => 0.490, ), 'hsv' => array( 'h' => 207.273, 's' => 0.611, 'v' => 0.706, ), 'cmy' => array( 'c' => 0.725, 'm' => 0.490, 'y' => 0.294, ), 'cmyk' => array( 'c' => 0.611, 'm' => 0.278, 'y' => 0.000, 'k' => 0.294, ), ),
			array( 'tan', '#D2B48C', 'rgb' => array( 'r' => 210, 'g' => 180, 'b' => 140, ), 'hsl' => array( 'h' => 34.286, 's' => 0.438, 'l' => 0.686, ), 'hsv' => array( 'h' => 34.286, 's' => 0.333, 'v' => 0.824, ), 'cmy' => array( 'c' => 0.176, 'm' => 0.294, 'y' => 0.451, ), 'cmyk' => array( 'c' => 0.000, 'm' => 0.143, 'y' => 0.333, 'k' => 0.176, ), ),
			array( 'teal', '#008080', 'rgb' => array( 'r' => 0, 'g' => 128, 'b' => 128, ), 'hsl' => array( 'h' => 180.000, 's' => 1.000, 'l' => 0.251, ), 'hsv' => array( 'h' => 180.000, 's' => 1.000, 'v' => 0.502, ), 'cmy' => array( 'c' => 1.000, 'm' => 0.498, 'y' => 0.498, ), 'cmyk' => array( 'c' => 1.000, 'm' => 0.000, 'y' => 0.000, 'k' => 0.498, ), ),
			array( 'thistle', '#D8BFD8', 'rgb' => array( 'r' => 216, 'g' => 191, 'b' => 216, ), 'hsl' => array( 'h' => 300.000, 's' => 0.243, 'l' => 0.798, ), 'hsv' => array( 'h' => 300.000, 's' => 0.116, 'v' => 0.847, ), 'cmy' => array( 'c' => 0.153, 'm' => 0.251, 'y' => 0.153, ), 'cmyk' => array( 'c' => 0.000, 'm' => 0.116, 'y' => 0.000, 'k' => 0.153, ), ),
			array( 'tomato', '#FF6347', 'rgb' => array( 'r' => 255, 'g' => 99, 'b' => 71, ), 'hsl' => array( 'h' => 9.130, 's' => 1.000, 'l' => 0.639, ), 'hsv' => array( 'h' => 9.130, 's' => 0.722, 'v' => 1.000, ), 'cmy' => array( 'c' => 0.000, 'm' => 0.612, 'y' => 0.722, ), 'cmyk' => array( 'c' => 0.000, 'm' => 0.612, 'y' => 0.722, 'k' => 0.000, ), ),
			array( 'turquoise', '#40E0D0', 'rgb' => array( 'r' => 64, 'g' => 224, 'b' => 208, ), 'hsl' => array( 'h' => 174.000, 's' => 0.721, 'l' => 0.565, ), 'hsv' => array( 'h' => 174.000, 's' => 0.714, 'v' => 0.878, ), 'cmy' => array( 'c' => 0.749, 'm' => 0.122, 'y' => 0.184, ), 'cmyk' => array( 'c' => 0.714, 'm' => 0.000, 'y' => 0.071, 'k' => 0.122, ), ),
			array( 'violet', '#EE82EE', 'rgb' => array( 'r' => 238, 'g' => 130, 'b' => 238, ), 'hsl' => array( 'h' => 300.000, 's' => 0.761, 'l' => 0.722, ), 'hsv' => array( 'h' => 300.000, 's' => 0.454, 'v' => 0.933, ), 'cmy' => array( 'c' => 0.067, 'm' => 0.490, 'y' => 0.067, ), 'cmyk' => array( 'c' => 0.000, 'm' => 0.454, 'y' => 0.000, 'k' => 0.067, ), ),
			array( 'wheat', '#F5DEB3', 'rgb' => array( 'r' => 245, 'g' => 222, 'b' => 179, ), 'hsl' => array( 'h' => 39.091, 's' => 0.767, 'l' => 0.831, ), 'hsv' => array( 'h' => 39.091, 's' => 0.269, 'v' => 0.961, ), 'cmy' => array( 'c' => 0.039, 'm' => 0.129, 'y' => 0.298, ), 'cmyk' => array( 'c' => 0.000, 'm' => 0.094, 'y' => 0.269, 'k' => 0.039, ), ),
			array( 'white', '#FFFFFF', 'rgb' => array( 'r' => 255, 'g' => 255, 'b' => 255, ), 'hsl' => array( 'h' => 0.000, 's' => 0.000, 'l' => 1.000, ), 'hsv' => array( 'h' => 0.000, 's' => 0.000, 'v' => 1.000, ), 'cmy' => array( 'c' => 0.000, 'm' => 0.000, 'y' => 0.000, ), 'cmyk' => array( 'c' => 0.000, 'm' => 0.000, 'y' => 0.000, 'k' => 0.000, ), ),
			array( 'whitesmoke', '#F5F5F5', 'rgb' => array( 'r' => 245, 'g' => 245, 'b' => 245, ), 'hsl' => array( 'h' => 0.000, 's' => 0.000, 'l' => 0.961, ), 'hsv' => array( 'h' => 0.000, 's' => 0.000, 'v' => 0.961, ), 'cmy' => array( 'c' => 0.039, 'm' => 0.039, 'y' => 0.039, ), 'cmyk' => array( 'c' => 0.000, 'm' => 0.000, 'y' => 0.000, 'k' => 0.039, ), ),
			array( 'yellow', '#FFFF00', 'rgb' => array( 'r' => 255, 'g' => 255, 'b' => 0, ), 'hsl' => array( 'h' => 60.000, 's' => 1.000, 'l' => 0.500, ), 'hsv' => array( 'h' => 60.000, 's' => 1.000, 'v' => 1.000, ), 'cmy' => array( 'c' => 0.000, 'm' => 0.000, 'y' => 1.000, ), 'cmyk' => array( 'c' => 0.000, 'm' => 0.000, 'y' => 1.000, 'k' => 0.000, ), ),
			array( 'yellowgreen', '#9ACD32', 'rgb' => array( 'r' => 154, 'g' => 205, 'b' => 50, ), 'hsl' => array( 'h' => 79.742, 's' => 0.608, 'l' => 0.500, ), 'hsv' => array( 'h' => 79.742, 's' => 0.756, 'v' => 0.804, ), 'cmy' => array( 'c' => 0.396, 'm' => 0.196, 'y' => 0.804, ), 'cmyk' => array( 'c' => 0.249, 'm' => 0.000, 'y' => 0.756, 'k' => 0.196, ), ),
		);
	}

	/**
	 * @param string $hex_1 HTML color #xxxxxx
	 * @param string $hex_2 HTML color #xxxxxx
	 * @param int $delta
	 * @return true if similar
	 */
	function isSimilar( $hex_1, $hex_2, $delta = 1 ) {
		if ( ( preg_match( '/^#?([a-fA-F0-9]{2})([a-fA-F0-9]{2})([a-fA-F0-9]{2})$/', $hex_1, $val_1 ) )
		  && ( preg_match( '/^#?([a-fA-F0-9]{2})([a-fA-F0-9]{2})([a-fA-F0-9]{2})$/', $hex_2, $val_2 ) ) ) {
			$ret = true;
			for ( $i = 1; $i < 4; $i++ ) {
				if ( abs( hexdec( $val_1[$i] ) - hexdec( $val_2[$i] ) ) > abs( $delta ) ) {
					$ret = false;
				}
			}
		} else {
			$ret = false;
		}
		return $ret;
	}


}

?>
